# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-code:
    name: Teste code
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Notre script Python
      run: |
            pwd
            ls
            cd .
            pwd
            ls
            python Guo_Madani_Trehout_Triolet.py
      shell: sh
